# Deployment Configuration for Data Science Multi-Agent System

agents:
  root_agent:
    enabled: true
    max_retries: 3
    timeout: 30
    description: "Main orchestration agent for routing and coordination"
    
  db_agent:
    enabled: true
    max_retries: 2
    timeout: 15
    description: "Database agent for SQL queries and data extraction"
    
  ds_agent:
    enabled: true
    max_retries: 2
    timeout: 20
    description: "Data science agent for analytics and visualization"
    
  bqml_agent:
    enabled: true
    max_retries: 2
    timeout: 25
    description: "BigQuery ML agent for machine learning tasks"

environment:
  log_level: "INFO"
  enable_monitoring: true
  health_check_interval: 60
  max_concurrent_requests: 10
  request_timeout: 120

database:
  project_id: "${GOOGLE_CLOUD_PROJECT}"
  dataset_id: "data_science_agents"
  location: "US"
  max_query_timeout: 300
  
monitoring:
  enabled: true
  metrics_collection: true
  alert_on_failure: true
  performance_tracking: true
  
security:
  authentication_required: true
  rate_limiting: true
  max_requests_per_minute: 60
  
scaling:
  auto_scaling: false
  min_instances: 1
  max_instances: 5
  target_cpu_utilization: 70